[package]
name = "mdopen"
version = "0.3.0"
edition = "2021"
description = "Preview markdown files in a browser"
repository = "https://github.com/immanelg/mdopen"
keywords = ["markdown"]
license = "BSD-3-Clause"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4", features = ["derive"] }
comrak = "0.21.0"
tiny_http = "0.12.0"
log = "0.4.21"
nanotemplate = "0.3.0"
anyhow = "1"
open = "5"
env_logger = "0.11.3"

[profile.release]
strip = true
