[package]
name = "mdopen"
edition = "2021"
version = "0.4.0"
description = "Preview markdown files in a browser"
keywords = ["markdown"]
license = "BSD-3-Clause"
repository = "https://github.com/immanelg/mdopen"

[dependencies]
env_logger = "0.11.3"
log = "0.4.21"
markdown = "1.0.0-alpha.16"
nanotemplate = "0.3.0"
open = "5"
tiny_http = "0.12.0"

[dependencies.clap]
version = "4"
features = ["derive"]

[profile.release]
strip = true
