name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --verbose
    - name: Run
      run: |
        RUST_LOG=debug ./target/debug/mdopen -- README.md > mdopen.log 2>mdopen_error.log &
        sleep 3
    - name: Test
      run: HOST=127.0.0.1 PORT=5032 cargo test
    - name: Logs
      run: |
        echo mdopen.log
        cat mdopen.log
        echo mdopen_error.log
        cat mdopen_error.log
